#!/bin/sh
set -exo pipefail

unzip windows-x86_64.zip
unzip BrogueLite-windows-x86_64.zip
cd BrogueLite-windows
wine brogue.exe
cd ..

unzip linux-x86_64.zip
tar -xaf BrogueLite-linux-x86_64.tar.gz
cd BrogueLite-linux
./brogue
cd ..

unzip macos-x86_64.zip
unzip -l BrogueLite-macos-x86_64.zip
